#!/usr/bin/env python3
"""Second pass: add data-fr for all remaining untranslated strings."""
import re, os

BASE = '/Users/ash/Projects/migusta'
PAGES = ['index.html', 'classes.html', 'methodology.html', 'teachers.html',
         'activities.html', 'cafe.html', 'about.html', 'accommodation.html',
         'faqs.html', 'blog.html', 'contact.html']

FR = {
    # ── INDEX ──
    '¡Hola! — est. 2005 · Sucre, Bolivia': '¡Hola! — est. 2005 · Sucre, Bolivie',
    'Probably the most': 'Probablement la plus',
    'fun &amp; friendly': 'fun &amp; accueillante',
    'Spanish School in Sucre!': "École d'espagnol à Sucre !",
    'Enjoy every lesson, immerse in the culture. Speak with confidence.': 'Appréciez chaque leçon, immergez-vous dans la culture. Parlez avec confiance.',
    'Our small group and private lessons combine real life conversation, grammar and Bolivian culture to help you learn faster and feel at home.': 'Nos cours en petits groupes et privés combinent conversation réelle, grammaire et culture bolivienne pour vous aider à apprendre plus vite.',
    'Face to Face Classes': 'Cours en présentiel',
    'our students, learning &amp; laughing ✨': 'nos étudiants, apprenant &amp; riant ✨',
    'happy students': 'étudiants heureux',
    'Sucre — our beautiful home 🇧🇴': 'Sucre — notre belle ville 🇧🇴',
    'class time 📚': 'en cours 📚',
    'Why Choose Us': 'Pourquoi nous choisir',
    'Spanish lessons should focus on the needs of each student — because everyone is individual and learns in their own way.': "Les cours d'espagnol doivent se concentrer sur les besoins de chaque étudiant — car chacun est unique et apprend à sa manière.",
    "Founded in 2005 by Elizabeth and Fernando, Me Gusta Spanish was built on a simple belief: that great teaching puts the student first. After six years of developing their methodology, they opened the school's doors in 2011 — and haven't looked back.": "Fondée en 2005 par Elizabeth et Fernando, Me Gusta Spanish repose sur une conviction simple : un bon enseignement met l'étudiant en premier. Après six ans de développement de leur méthodologie, ils ont ouvert l'école en 2011.",
    'We change, improve and innovate every year. Our teachers are native Bolivian speakers who bring not just language, but culture, warmth and context to every single lesson.': "Nous changeons, améliorons et innovons chaque année. Nos professeurs boliviens apportent non seulement la langue, mais aussi la culture et la chaleur à chaque leçon.",
    'native instructors': 'professeurs natifs',
    'cultural immersion': 'immersion culturelle',
    'host families': "familles d'accueil",
    'beginner to advanced': 'débutant à avancé',
    'What we offer': 'Ce que nous offrons',
    'Two ways to <em>learn</em>': 'Deux façons d\'<em>apprendre</em>',
    'Learn Spanish in Sucre — the heart of language and culture. Join our in-person classes and live the language every day alongside native teachers and an international community of students.': "Apprenez l'espagnol à Sucre — le cœur de la langue et de la culture. Rejoignez nos cours en présentiel et vivez la langue chaque jour.",
    'Learn More →': 'En savoir plus →',
    'Millions of people around the world are learning Spanish online. Our interactive sessions with native Bolivian teachers bring the same warmth and results — directly to your screen.': "Des millions de personnes apprennent l'espagnol en ligne. Nos sessions interactives avec des professeurs boliviens natifs offrent la même chaleur et les mêmes résultats — directement sur votre écran.",
    'years of teaching': "années d'enseignement",
    'students registered': 'étudiants inscrits',
    'native Bolivian teachers': 'professeurs boliviens natifs',
    "Don't just take our word for it": 'Ne nous croyez pas sur parole',
    'What our <em>students</em> say': 'Ce que disent nos <em>étudiants</em>',
    'Me Gusta completely changed how I feel about language learning. Jhosmar had me holding real conversations within a week. I arrived nervous and left fluent enough to travel Bolivia alone.': "Me Gusta a complètement changé ma vision de l'apprentissage des langues. Jhosmar m'a fait tenir de vraies conversations en une semaine.",
    'Australia · 3 weeks in-person': 'Australie · 3 semaines en présentiel',
    'Staying with a host family while taking classes with Andrea was honestly one of the best decisions of my life. The combination of classroom learning and dinner-table Spanish is unbeatable.': "Séjourner dans une famille d'accueil tout en prenant des cours avec Andrea a été l'une des meilleures décisions de ma vie.",
    'Canada · Host family + classes': "Canada · Famille d'accueil + cours",
    "Yhamyle is extraordinary. I'd tried other schools before and always felt lost. Her patience and structured approach gave me the confidence I'd been missing for years. I still take online lessons now.": "Yhamyle est extraordinaire. J'avais essayé d'autres écoles avant et me sentais toujours perdu. Sa patience m'a donné la confiance qui me manquait.",
    'Germany · Online classes': 'Allemagne · Cours en ligne',
    'Read our Google Reviews': 'Lire nos avis Google',
    "hundreds of happy students — see what they're saying ⭐": "des centaines d'étudiants satisfaits — lisez leurs avis ⭐",
    'Learn online, anytime': 'Apprenez en ligne, à tout moment',
    'The best tutors <em>in town</em>': 'Les meilleurs professeurs <em>de la ville</em>',
    'Register to access your account where you can view and manage all your classes. Never before has learning Spanish from home been so effective — or so enjoyable.': "Inscrivez-vous pour accéder à votre compte où vous pouvez voir et gérer tous vos cours. Jamais apprendre l'espagnol depuis chez soi n'a été aussi efficace.",
    'Register now and save!': "Inscrivez-vous et économisez !",
    'members': 'membres',
    'class types': 'types de cours',
    'video lessons': 'cours vidéo',
    'average rating': 'note moyenne',
    '¿Eres profesor de español?': '¿Eres profesor de español?',
    "Are you a Spanish teacher looking for a school that truly values your craft? We're always interested in hearing from passionate, experienced educators who share our philosophy of student-first learning.": "Vous êtes professeur d'espagnol et cherchez une école qui valorise votre métier ? Nous sommes toujours à la recherche d'éducateurs passionnés.",
    "send us your CV and let's talk ✉️": "envoyez-nous votre CV et discutons ✉️",
    'Get in Touch': 'Contactez-nous',
    "Sea parte del proyecto 'Me Gusta'": "Sea parte del proyecto 'Me Gusta'",
    "Request information and become part of a worldwide network of schools and accommodations. We're building something special — and we'd love you to be part of it.": "Demandez des informations et rejoignez un réseau mondial d'écoles et d'hébergements. Nous construisons quelque chose de spécial.",
    'partners across South America &amp; beyond 🌎': 'partenaires en Amérique du Sud &amp; au-delà 🌎',
    'Find Out More': 'En savoir plus',
    'Probably the most fun and friendly Spanish school in Sucre, Bolivia. Helping students speak with confidence since 2005.': "Probablement l'école d'espagnol la plus amusante et accueillante de Sucre, Bolivie. Nous aidons les étudiants à parler avec confiance depuis 2005.",
    'Pages': 'Pages',
    'Types of Classes': 'Types de cours',
    'Our Teachers': 'Nos professeurs',
    'Face-to-Face': 'En présentiel',
    'Host Families': "Familles d'accueil",
    'Private Lessons': 'Cours particuliers',
    'Free Trial Class': "Cours d'essai gratuit",
    'Junín 333, Sucre, Bolivia': 'Junín 333, Sucre, Bolivie',
    'WhatsApp Us': 'WhatsApp',
    '© 2025 Me Gusta Spanish School, Sucre, Bolivia ☀️': '© 2025 Me Gusta Spanish School, Sucre, Bolivie ☀️',
    'Made with ❤️ in Sucre': 'Fait avec ❤️ à Sucre',

    # ── CLASSES ──
    'find the class that fits you': 'trouvez le cours qui vous convient',
    'Types of': 'Types de',
    'Our Spanish classes are divided into face-to-face classes in Sucre and online classes from anywhere in the world. Same teachers. Same warmth. Two ways to learn.': "Nos cours d'espagnol se divisent en cours en présentiel à Sucre et en ligne depuis le monde entier. Mêmes professeurs. Même chaleur. Deux façons d'apprendre.",
    'small groups, big results ✨': 'petits groupes, grands résultats ✨',
    'culture + language ✨': 'culture + langue ✨',
    'real conversations from day one ✨': 'vraies conversations dès le premier jour ✨',
    'Request a Trial': "Demander un essai",
    'In Sucre, Bolivia': 'À Sucre, Bolivie',
    'Learn Spanish in the <em>heart</em> of South America': "Apprenez l'espagnol au <em>cœur</em> de l'Amérique du Sud",
    "Join our in-person Spanish classes and live the language every day. Sucre is one of Bolivia's most beautiful colonial cities — a perfect backdrop for language learning, cultural discovery, and making memories.": "Rejoignez nos cours d'espagnol en présentiel et vivez la langue chaque jour. Sucre est l'une des plus belles villes coloniales de Bolivie.",
    "Our native Bolivian teachers bring grammar, conversation and culture into every session. Whether you're a complete beginner or polishing your fluency, we tailor every lesson to you.": "Nos professeurs boliviens natifs intègrent grammaire, conversation et culture dans chaque session. Que vous soyez débutant complet ou que vous perfectionniez votre fluidité, nous adaptons chaque leçon à vous.",
    'native teachers': 'professeurs natifs',
    'Junín 333, Sucre': 'Junín 333, Sucre',
    'our classroom in Sucre 📍': 'notre salle de classe à Sucre 📍',
    'Choose your <em>format</em>': 'Choisissez votre <em>format</em>',
    'Private': 'Privé',
    'One-to-one lessons entirely tailored to your pace, goals and interests. The fastest way to progress.': 'Cours individuels entièrement adaptés à votre rythme, vos objectifs et vos intérêts. La façon la plus rapide de progresser.',
    'Couples': 'Couples',
    'Learn together with a partner, friend or family member. Shared classes at a shared pace — still personal.': 'Apprenez avec un partenaire, ami ou membre de la famille. Cours partagés à un rythme commun — toujours personnels.',
    'Groups': 'Groupes',
    'Small group classes with international students at a similar level. Great for conversation practice and making friends.': "Cours en petits groupes avec des étudiants internationaux de niveau similaire. Idéal pour la conversation et se faire des amis.",
    'Children &amp; Teens': 'Enfants &amp; Ados',
    'Age-appropriate programmes from 6 years old, taught by specialist instructors who know how to make learning fun for young minds.': "Programmes adaptés dès 6 ans, enseignés par des instructeurs spécialisés qui savent rendre l'apprentissage amusant.",
    'Specialised': 'Spécialisé',
    'Business Spanish, medical terminology, travel Spanish and more. Built around your specific professional or personal needs.': "Espagnol des affaires, terminologie médicale, espagnol de voyage et plus. Adapté à vos besoins professionnels ou personnels.",
    'Companies': 'Entreprises',
    'Corporate Spanish courses for teams — delivered on-site or at our school. Flexible scheduling to fit around your business.': "Cours d'espagnol pour entreprises — sur site ou dans notre école. Horaires flexibles adaptés à votre activité.",
    'how to get started with face-to-face classes 👇': 'comment commencer les cours en présentiel 👇',
    'Request a trial': "Demander un essai",
    'Fill in the form below and request your free trial class.': "Remplissez le formulaire ci-dessous et demandez votre cours d'essai gratuit.",
    'Book your sessions': 'Réservez vos sessions',
    'Choose how many sessions you need and make your booking.': 'Choisissez le nombre de sessions et faites votre réservation.',
    'Set your schedule': 'Définissez votre emploi du temps',
    'Agree your class times with your teacher — flexible to suit you.': "Convenez de vos horaires de cours avec votre professeur — flexibles selon vos besoins.",
    'Start learning!': "Commencez à apprendre !",
    'Come to Junín 333 and start your Spanish adventure.': "Venez au Junín 333 et commencez votre aventure en espagnol.",
    'Learn from anywhere': "Apprenez de n'importe où",
    'Online Classes with <em>native teachers</em>': 'Cours en ligne avec des <em>professeurs natifs</em>',
    'Millions of people around the world are taking Spanish classes online — and never before has it been so effective. Our interactive online sessions with native Bolivian teachers deliver the same personal approach and real results, wherever you are in the world.': "Des millions de personnes suivent des cours d'espagnol en ligne — et jamais cela n'a été aussi efficace. Nos sessions interactives avec des professeurs boliviens offrent la même approche personnelle, où que vous soyez.",
    'Choose your format, pick your timezone, and start learning. It really is that simple.': "Choisissez votre format, votre fuseau horaire, et commencez. C'est aussi simple que ça.",
    'private lessons': 'cours privés',
    'any timezone': 'tout fuseau horaire',
    'flexible schedule': 'horaires flexibles',
    'learning from home 💻': 'apprendre depuis chez soi 💻',
    'how to start with online classes 👇': 'comment commencer les cours en ligne 👇',
    'Request a free trial': "Demander un essai gratuit",
    'Fill in the form below to request your complimentary first class.': "Remplissez le formulaire ci-dessous pour demander votre premier cours gratuit.",
    'Buy your sessions': 'Achetez vos sessions',
    'Choose the number of sessions that works for you — 1 to 10.': 'Choisissez le nombre de sessions qui vous convient — de 1 à 10.',
    'Agree a schedule': "Convenir d'un emploi du temps",
    'Coordinate with your teacher to find the perfect class times.': 'Coordonnez avec votre professeur pour trouver les horaires parfaits.',
    'Log in and start your immersive online Spanish journey.': "Connectez-vous et commencez votre voyage immersif en espagnol en ligne.",
    'First class on us': 'Premier cours offert',
    'Request your <em>free trial</em> class': 'Demandez votre cours d\'<em>essai gratuit</em>',
    'Not sure which class is right for you? Start with a free trial. Meet your teacher, get a feel for our style, and ask us anything. No commitment needed.': "Pas sûr(e) de quel cours vous convient ? Commencez par un essai gratuit. Rencontrez votre professeur et posez-nous vos questions. Sans engagement.",
    'we usually respond within a few hours ⚡': 'nous répondons généralement en quelques heures ⚡',
    'completely free': 'entièrement gratuit',
    'no commitment': 'sans engagement',
    'face-to-face or online': 'en présentiel ou en ligne',
    'Request a <em>Trial Class</em>': "Demander un <em>cours d'essai</em>",
    'Your Name': 'Votre nom',
    'Email Address': 'Adresse email',
    'Class Type': 'Type de cours',
    'Online': 'En ligne',
    'Format': 'Format',
    'No. of Sessions': 'Nombre de sessions',
    'Your Timezone': 'Votre fuseau horaire',
    'Message (optional)': 'Message (facultatif)',
    'Request Your Trial Class Now →': "Demander votre cours d'essai →",

    # ── METHODOLOGY ──
    'The': 'La',
    'Me Gusta': 'Me Gusta',
    'Method': 'Méthode',
    "After 17 years of teaching Spanish to students from all over the world, we've built a methodology that actually works — because it's built around you, not a textbook.": "Après 17 ans d'enseignement de l'espagnol à des étudiants du monde entier, nous avons construit une méthodologie qui fonctionne vraiment — car elle est construite autour de vous, pas d'un manuel.",
    'Start Learning →': 'Commencer à apprendre →',
    'learning that actually sticks ✨': 'un apprentissage qui reste ✨',
    "Everyone can learn to speak Spanish — no matter what. After 17 years of teaching, we've never met a student who couldn't.": "Tout le monde peut apprendre l'espagnol — quoi qu'il arrive. En 17 ans d'enseignement, nous n'avons jamais rencontré un étudiant qui n'y arrivait pas.",
    '— Elizabeth &amp; Fernando, founders of Me Gusta Spanish': '— Elizabeth &amp; Fernando, fondateurs de Me Gusta Spanish',
    'Our philosophy': 'Notre philosophie',
    "Learning a language is like learning a sport or an instrument — it requires constant practice and commitment to see long-term results. But that doesn't mean it can't be fun. In fact, we think the two go hand in hand.": "Apprendre une langue, c'est comme apprendre un sport ou un instrument — cela demande une pratique constante. Mais cela ne veut pas dire que ça ne peut pas être amusant.",
    "Every year, we change, implement, improve and innovate. Our methodology has been refined through thousands of hours in the classroom, and it's shaped around one core principle: your lessons should be about you.": "Chaque année, nous changeons, améliorons et innovons. Notre méthodologie a été affinée par des milliers d'heures en classe, autour d'un principe fondamental : vos cours doivent être centrés sur vous.",
    'since 2005': 'depuis 2005',
    'student-first': "l'étudiant d'abord",
    'proven results': 'résultats prouvés',
    'always evolving': 'en constante évolution',
    'The secret ingredients': 'Les ingrédients secrets',
    'Four things every <em>successful</em> learner has': 'Quatre choses que chaque apprenant <em>réussi</em> possède',
    'Motivation': 'Motivation',
    "Knowing why you're learning Spanish is the spark that keeps everything going. We help you reconnect with that reason in every lesson.": "Savoir pourquoi vous apprenez l'espagnol est l'étincelle qui fait tout avancer. Nous vous aidons à renouer avec cette raison à chaque leçon.",
    'Commitment': 'Engagement',
    'Regular, consistent study is the single most important factor in language progress. Even 30 minutes a day makes an enormous difference.': "L'étude régulière et constante est le facteur le plus important dans la progression linguistique. Même 30 minutes par jour font une énorme différence.",
    'Discipline': 'Discipline',
    'Structure and routine help your brain retain new language patterns. We help you build habits that make learning feel effortless.': "La structure et la routine aident votre cerveau à retenir de nouveaux schémas linguistiques. Nous vous aidons à créer des habitudes qui rendent l'apprentissage naturel.",
    'Forget the Grammar': 'Oubliez la grammaire',
    'The biggest barrier to fluency is being afraid to make mistakes. We create a space where you can speak freely — and grammar follows naturally.': "Le plus grand obstacle à la fluidité est la peur de faire des erreurs. Nous créons un espace où vous pouvez parler librement — et la grammaire suit naturellement.",
    'How every class is structured': 'Comment chaque cours est structuré',
    'Theory <em>&amp;</em> Practice — every single lesson': 'Théorie <em>&amp;</em> pratique — à chaque cours',
    'Part One': 'Première partie',
    'Theoretical': 'Théorique',
    "Every lesson opens with grammar explanation and targeted practice. Topics are organised by logical progression and difficulty, so you always build on what you already know — never jumping ahead before you're ready.": "Chaque cours commence par une explication grammaticale et de la pratique ciblée. Les sujets sont organisés par progression logique, donc vous construisez toujours sur ce que vous savez déjà.",
    'Part Two': 'Deuxième partie',
    'Practical': 'Pratique',
    "The second half brings the language to life through reading, songs, games, real-life situations and cultural notes. These activities engage your memory in a way that dry repetition never could — because you're actually using the language.": "La seconde moitié donne vie à la langue à travers la lecture, les chansons, les jeux, des situations réelles et des notes culturelles — parce que vous utilisez vraiment la langue.",
    'little tricks, big results ✨': 'petites astuces, grands résultats ✨',
    'Memory techniques we love': 'Techniques de mémoire que nous adorons',
    'Making new words <em>stick</em>': 'Faire <em>retenir</em> les nouveaux mots',
    'We teach you how to build a personal vocabulary that stays with you — using techniques drawn from memory science and our own years of experience in the classroom.': "Nous vous apprenons à construire un vocabulaire personnel qui reste — en utilisant des techniques issues de la science de la mémoire et de notre expérience.",
    'Mental Associations': 'Associations mentales',
    'Connect new Spanish words to sounds, images or stories that already mean something to you. Your brain remembers meaning far better than isolated vocabulary lists.': "Connectez les nouveaux mots espagnols à des sons, images ou histoires qui ont déjà un sens pour vous. Votre cerveau retient le sens bien mieux que des listes de vocabulaire isolées.",
    'Flashcards with Context': 'Cartes mémoire avec contexte',
    'Not simple translation cards — but two-sided cards with the word used in a real sentence. Context is everything. You remember how a word feels, not just what it means.': "Pas de simples cartes de traduction — mais des cartes avec le mot utilisé dans une vraie phrase. Le contexte est tout. Vous retenez comment un mot se ressent, pas seulement ce qu'il signifie.",
    'think about how children learn...': 'pensez à comment les enfants apprennent...',
    'Children speak fluently without ever <em>studying grammar.</em><br>So can you.': 'Les enfants parlent couramment sans jamais <em>étudier la grammaire.</em><br>Vous aussi.',
    'Children learn their first language through interaction, listening, imitation and feedback — not through memorising rules. Our methodology draws on this natural process. We give you grammar as a tool, not as the destination. Real conversation, real culture, real Spanish — from your very first lesson.': "Les enfants apprennent leur première langue par l'interaction, l'écoute, l'imitation et le retour — pas en mémorisant des règles. Notre méthodologie s'inspire de ce processus naturel. Vraie conversation, vraie culture, vrai espagnol — dès votre première leçon.",
    'See Our Classes →': 'Voir nos cours →',
    'Ready to experience the <em>Me Gusta</em> method for yourself?': 'Prêt à découvrir la méthode <em>Me Gusta</em> par vous-même ?',
    'Start with a free trial class — no commitment, no pressure. Just you, your teacher, and a genuinely great first lesson.': "Commencez par un cours d'essai gratuit — sans engagement, sans pression. Juste vous, votre professeur, et une première leçon vraiment excellente.",
    'Request a Free Trial': "Demander un essai gratuit",
    'first class completely free ✨': 'premier cours entièrement gratuit ✨',

    # ── TEACHERS ──
    'the people who make it happen': 'les personnes qui font la différence',
    'Meet our <em>teachers</em>': 'Rencontrez nos <em>professeurs</em>',
    'Every teacher at Me Gusta is personally trained by Elizabeth and Fernando. Not just fluent — warm, patient, and genuinely invested in your progress.': "Chaque professeur de Me Gusta est formé personnellement par Elizabeth et Fernando. Pas seulement compétent — chaleureux, patient et vraiment investi dans vos progrès.",
    'Kiara is one of the most versatile teachers at Me Gusta — equally at home with complete beginners and near-fluent speakers. She has a natural ability to read where a student is and adapt on the spot, creating classes that always feel tailored, never generic.': "Kiara est l'une des professeures les plus polyvalentes de Me Gusta — aussi à l'aise avec les débutants complets qu'avec les locuteurs quasi-fluents. Elle a une capacité naturelle à s'adapter, créant des cours toujours sur mesure.",
    'always involved': 'toujours impliqués',
    "Elizabeth and Fernando didn't step back when the school grew — they stepped in. Both founders continue to teach regularly, covering classes and working with advanced students who want to go deep into the language.": "Elizabeth et Fernando ne se sont pas mis en retrait quand l'école a grandi — ils se sont davantage impliqués. Les deux fondateurs continuent d'enseigner régulièrement.",
    'ready to start? ✨': 'prêt à commencer ? ✨',
    'Find the right teacher for you': 'Trouvez le professeur idéal pour vous',
    "Tell us about your level, your goals, and how you learn best — and we'll match you with the perfect teacher from day one.": "Parlez-nous de votre niveau, vos objectifs, et comment vous apprenez le mieux — et nous vous associerons au professeur parfait dès le premier jour.",
    'Book a trial class →': "Réserver un cours d'essai →",
    'Sucre, Bolivia ☀️': 'Sucre, Bolivie ☀️',

    # ── ACTIVITIES ──
    "Language is more than grammar — it's music, food, markets, and conversation at midnight. Our activities put you in the middle of it all.": "La langue, c'est plus que la grammaire — c'est la musique, la nourriture, les marchés et les conversations à minuit. Nos activités vous placent au cœur de tout cela.",
    'eight ways to immerse': "huit façons de s'immerger",
    'The full <em>experience</em>': "L'<em>expérience</em> complète",
    "These aren't extras — they're where the real learning happens. Every activity is led by a teacher or local guide, and everything runs in Spanish.": "Ce ne sont pas des extras — c'est là que le vrai apprentissage se fait. Chaque activité est menée par un professeur ou un guide local, et tout se fait en espagnol.",
    'Every Tuesday · 3 hrs': 'Chaque mardi · 3h',
    'Food & Culture': 'Gastronomie & Culture',
    'Cook a traditional Bolivian meal from scratch in the Me Gusta café kitchen. Your teacher guides you through the whole process in Spanish — shopping vocabulary, recipe instructions, food culture. Then you eat what you made.': "Cuisinez un repas bolivien traditionnel dans la cuisine du café Me Gusta. Votre professeur vous guide en espagnol — vocabulaire des courses, instructions de recette, culture culinaire. Puis vous mangez ce que vous avez préparé.",
    'Every Tuesday': 'Chaque mardi',
    'All levels welcome': 'Tous niveaux bienvenus',
    'Saturday mornings': 'Samedis matin',
    'City & Culture': 'Ville & Culture',
    "An early-morning guided walk through Sucre's Mercado Central with one of our teachers. You'll learn the names of every vegetable, spice, and cut of meat — and how to haggle politely.": "Une promenade matinale guidée à travers le Mercado Central de Sucre avec l'un de nos professeurs. Vous apprendrez le nom de chaque légume, épice et morceau de viande.",
    'Saturday 8am': 'Samedi 8h',
    'Mon & Thu · 2 hrs': 'Lun & Jeu · 2h',
    'History & Architecture': 'Histoire & Architecture',
    'Walk the White City with a teacher-guide who brings its colonial history to life — entirely in Spanish. From the Plaza 25 de Mayo to hidden courtyards and rooftop views.': "Parcourez la Ville Blanche avec un professeur-guide qui donne vie à son histoire coloniale — entièrement en espagnol.",
    'Mon & Thursday': 'Lun & Jeudi',
    'Every Friday · 2 hrs': 'Chaque vendredi · 2h',
    'Music & Dance': 'Musique & Danse',
    'Weekly dance session with a local instructor. Your teacher translates moves and cultural context. No experience needed — just be ready to laugh and move.': "Session de danse hebdomadaire avec un instructeur local. Votre professeur traduit les mouvements et le contexte culturel. Aucune expérience requise.",
    'Every Friday': 'Chaque vendredi',
    'All welcome': 'Tous bienvenus',
    'Wednesday evenings': 'Mercredis soir',
    'Film & Discussion': 'Film & Discussion',
    'A Latin American film screened in the café, followed by an open discussion in Spanish. A brilliant way to hear natural speech, absorb vocabulary in context, and talk about things that matter.': "Un film latino-américain projeté au café, suivi d'une discussion ouverte en espagnol. Une excellente façon d'entendre la langue naturelle et d'absorber du vocabulaire en contexte.",
    'Wednesday 7pm': 'Mercredi 19h',
    'Intermediate+': 'Intermédiaire+',
    'Thursdays · from 6pm': 'Jeudis · à partir de 18h',
    'Speaking Practice': 'Pratique orale',
    "Informal gathering at the café with teachers, students, and local guests. No formal structure — just real conversation, great coffee, and the kind of connections that stay with you long after you've left Sucre.": "Rassemblement informel au café avec des professeurs, étudiants et invités locaux. Pas de structure formelle — juste de vraies conversations et un bon café.",
    'Every Thursday': 'Chaque jeudi',
    'From 6pm': 'À partir de 18h',
    'Every Sunday · full day': 'Chaque dimanche · journée entière',
    'Excursion': 'Excursion',
    "A full-day Sunday excursion to Tarabuco, 1 hour from Sucre. One of Bolivia's most vibrant indigenous markets — Jalq'a and Yampara communities gather here in traditional dress. Your teacher guides you through, Spanish only.": "Excursion du dimanche à Tarabuco, à 1 heure de Sucre. L'un des marchés indigènes les plus vibrants de Bolivie. Votre professeur vous guide, en espagnol uniquement.",
    'Every Sunday': 'Chaque dimanche',
    'Transport included': 'Transport inclus',
    'By arrangement': 'Sur arrangement',
    'Language & Art': 'Langue & Art',
    "A Spanish-language photography walk through Sucre. You describe what you see, what light does to a building, what a person's expression makes you feel. Descriptive vocabulary, adjectives, storytelling — all without feeling like a lesson.": "Une promenade photo en espagnol à travers Sucre. Vous décrivez ce que vous voyez, la lumière sur un bâtiment, l'expression d'une personne. Vocabulaire descriptif, adjectifs, narration — sans jamais avoir l'impression d'une leçon.",
    'Flexible scheduling': 'Horaires flexibles',
    'Small groups': 'Petits groupes',
    'Simple to <em>join</em>': 'Simple à <em>rejoindre</em>',
    'Sign up': "S'inscrire",
    'Tell us which activities interest you when you register, or drop us a message anytime. Most activities are free or low cost for enrolled students.': "Dites-nous quelles activités vous intéressent lors de votre inscription, ou envoyez-nous un message. La plupart des activités sont gratuites ou à faible coût pour les étudiants inscrits.",
    'Show up': 'Présentez-vous',
    'Everything runs from the school or the café. No complex logistics — we keep it easy so the focus stays on the experience, not the planning.': "Tout part de l'école ou du café. Pas de logistique complexe — nous gardons les choses simples pour que l'accent reste sur l'expérience.",
    'Speak Spanish': "Parlez espagnol",
    "Every activity runs entirely in Spanish. Your teacher is always with you — there to help, not to correct. It's the fastest way to build confidence outside a classroom.": "Chaque activité se déroule entièrement en espagnol. Votre professeur est toujours avec vous — pour aider, pas pour corriger. C'est la façon la plus rapide de gagner en confiance.",
    'Good to know': 'Bon à savoir',
    "All activities are included in your study package or available for a small additional fee. Schedules may vary seasonally — ask us when you register and we'll confirm what's running during your stay.": "Toutes les activités sont incluses dans votre forfait ou disponibles pour un petit supplément. Les horaires peuvent varier selon la saison — demandez-nous lors de votre inscription.",
    'ready for the full experience? ✨': "prêt pour l'expérience complète ? ✨",
    'Book your place in Sucre': 'Réservez votre place à Sucre',
    'Classes, activities, café, accommodation — it all lives here. Come for a week or stay for a month.': "Cours, activités, café, hébergement — tout est ici. Venez pour une semaine ou restez un mois.",

    # ── CAFÉ ──
    'Café · Sucre, Bolivia': 'Café · Sucre, Bolivie',
    'Where coffee<br><em>tastes different</em>': 'Où le café a<br><em>un autre goût</em>',
    'Single-origin Bolivian beans, brewed slowly. A colonial courtyard. A place to learn, linger, and let the morning unfold.': "Grains boliviens d'origine unique, infusés lentement. Une cour coloniale. Un endroit pour apprendre, flâner et laisser la matinée se dérouler.",
    'Single-origin coffee': "Café d'origine unique",
    'Open-air courtyard': 'Cour en plein air',
    'Bolivar #603, Sucre': 'Bolivar #603, Sucre',
    'See the menu': 'Voir le menu',
    'Open <strong>Mon–Sat, 7am–7pm</strong>': 'Ouvert <strong>Lun–Sam, 7h–19h</strong>',
    'the space': "l'espace",
    "Housed in a 19th-century colonial building in the heart of Sucre, our café is more than a coffee stop — it's a space to work, read, or simply breathe.": "Installé dans un bâtiment colonial du XIXe siècle au cœur de Sucre, notre café est plus qu'un arrêt café — c'est un espace pour travailler, lire ou simplement respirer.",
    'Colonial Architecture': 'Architecture coloniale',
    'Original 19th-century stonework, arched doorways, and terracotta floors.': "Maçonnerie originale du XIXe siècle, portes en arche et sols en terre cuite.",
    'Free WiFi': 'WiFi gratuit',
    'Fast, reliable connection — ideal for students and remote workers.': 'Connexion rapide et fiable — idéale pour les étudiants et les travailleurs à distance.',
    'Open-Air Courtyard': 'Cour en plein air',
    'Shaded tables under the open sky — the finest office in Sucre.': "Tables ombragées sous le ciel ouvert — le plus beau bureau de Sucre.",
    'from bean to cup': 'du grain à la tasse',
    'Coffee with a <em>story</em>': 'Un café avec une <em>histoire</em>',
    'Every cup is sourced from regions with extraordinary growing conditions — from the misty valleys of Bolivia to the fields of northern Italy.': "Chaque tasse provient de régions aux conditions de culture extraordinaires — des vallées brumeuses de Bolivie aux champs du nord de l'Italie.",
    'Yungas, Bolivia': 'Yungas, Bolivie',
    'Yungas Valley': 'Vallée des Yungas',
    'Grown in the cloud forests of the Bolivian Andes at 1,500–2,000m. Rich volcanic soil and high altitude produce a coffee of exceptional clarity and complexity.': "Cultivé dans les forêts de nuages des Andes boliviennes à 1 500–2 000 m. Sol volcanique riche et haute altitude produisent un café d'une clarté et complexité exceptionnelles.",
    'Dark chocolate': 'Chocolat noir',
    'Citrus': 'Agrumes',
    'Floral': 'Floral',
    'Caranavi, Bolivia': 'Caranavi, Bolivie',
    'Caranavi Hills': 'Collines de Caranavi',
    "Bolivia's most celebrated coffee-growing region. Fertile foothills and an ideal microclimate produce a naturally sweet, full-bodied cup that's become a world favourite.": "La région caféière la plus célèbre de Bolivie. Des contreforts fertiles et un microclimat idéal produisent une tasse naturellement sucrée et corsée.",
    'Brown sugar': 'Sucre brun',
    'Walnut': 'Noix',
    'Stone fruit': 'Fruits à noyau',
    'Northern Italy': 'Nord de l\'Italie',
    "Italy's most iconic coffee house, roasting since 1895. For those who want that classic, robust Italian espresso — smooth, strong, and completely reliable.": "La maison de café la plus emblématique d'Italie, torréfaction depuis 1895. Pour ceux qui veulent un espresso italien classique — doux, fort et fiable.",
    'Roasted nuts': 'Fruits secs grillés',
    'Caramel': 'Caramel',
    'Classic espresso': 'Espresso classique',
    "what we're serving": 'ce que nous servons',
    'Our <em>Menu</em>': 'Notre <em>menu</em>',
    "Everything on the menu is made with care. Our food is baked fresh every morning — if it isn't fresh, we don't serve it.": "Tout sur le menu est fait avec soin. Nos plats sont préparés frais chaque matin — si ce n'est pas frais, nous ne le servons pas.",
    'All food baked fresh this morning': 'Tout est préparé frais ce matin',
    'Coffee &amp; Hot Drinks': 'Café &amp; boissons chaudes',
    'Espresso cut with warm milk — balanced and beautiful.': "Espresso coupé avec du lait chaud — équilibré et beau.",
    'Single or double. Bolivian or Lavazza — your choice.': 'Simple ou double. Bolivien ou Lavazza — à vous de choisir.',
    'Velvety micro-foam over double ristretto. Our most popular order.': 'Micro-mousse veloutée sur double ristretto. Notre commande la plus populaire.',
    'Café Latte': 'Café Latte',
    'Smooth and milky — perfect for a long study session.': "Doux et lacté — parfait pour une longue session d'étude.",
    'Long and clean. Hot or iced.': 'Long et pur. Chaud ou glacé.',
    'Bolivian Cold Brew': 'Cold Brew bolivien',
    'Slow-steeped 18 hours using our Caranavi beans. Rich, smooth, no bitterness.': 'Infusé lentement 18 heures avec nos grains de Caranavi. Riche, doux, sans amertume.',
    'The Bolivian classic. Helps with altitude, tastes wonderful, deeply local.': "Le classique bolivien. Aide avec l'altitude, goût merveilleux, profondément local.",
    'Food — Baked Fresh Daily': 'Nourriture — fraîche chaque jour',
    'Toasted ciabatta with roasted vegetables, mozzarella, and pesto.': 'Ciabatta grillée avec légumes rôtis, mozzarella et pesto.',
    'Meat Esfirra': 'Esfirra à la viande',
    'South American classic — baked pastry filled with seasoned minced beef and spices.': "Classique sud-américain — pâtisserie fourrée au bœuf haché assaisonné et aux épices.",
    'Red Velvet Cake': 'Red Velvet Cake',
    'Rich red velvet sponge with cream cheese frosting. The one regulars come back for.': "Gâteau red velvet riche avec glaçage au cream cheese. Celui pour lequel les habitués reviennent.",
    'Carrot Cake': 'Carrot Cake',
    'Moist, spiced, topped with cream cheese frosting and crushed walnuts.': 'Moelleux, épicé, garni de glaçage au cream cheese et noix concassées.',
    'Chocolate Brownie': 'Brownie au chocolat',
    'Dense, fudgy, real dark Bolivian chocolate. Served warm. Dangerous.': 'Dense, fondant, vrai chocolat noir bolivien. Servi chaud. Dangereux.',
    'Seasonal Fruit Bowl': 'Bol de fruits de saison',
    "Whatever Bolivia's markets have to offer today. Always fresh, always colourful.": "Ce que les marchés de Bolivie offrent aujourd'hui. Toujours frais, toujours coloré.",
    'a taste of the café': 'un aperçu du café',
    'Come and <em>see</em> for yourself': 'Venez <em>voir</em> par vous-même',
    'Free WiFi always on': 'WiFi gratuit toujours disponible',
    'for students &amp; guests': 'pour étudiants &amp; visiteurs',
    'A unique <em>study space</em> unlike any other': 'Un espace <em>d\'étude</em> unique en son genre',
    'Me Gusta Café is open to all students as a dedicated study and relaxation space. Between classes — or after — pull up a chair, order something delicious, connect to the WiFi, and let the language sink in.': "Le café Me Gusta est ouvert à tous les étudiants comme espace d'étude et de détente. Entre les cours — ou après — prenez une chaise, commandez quelque chose de délicieux, et laissez la langue s'imprégner.",
    "Many students find that reviewing vocabulary over a cortado, or practising conversation over lunch, is where the real learning happens. The café is more than a café — it's part of the school.": "Beaucoup d'étudiants trouvent que réviser le vocabulaire devant un cortado est là où le vrai apprentissage se fait. Le café est plus qu'un café — il fait partie de l'école.",
    'Fast WiFi': 'WiFi rapide',
    'Reliable high-speed internet, free for all students': 'Internet haut débit fiable, gratuit pour tous les étudiants',
    'Power Outlets': 'Prises électriques',
    'Charging points throughout the café and courtyard': 'Points de charge dans tout le café et la cour',
    'Spanish Library': 'Bibliothèque espagnole',
    'Graded readers and dictionaries to borrow': 'Lecteurs gradués et dictionnaires à emprunter',
    'Language Exchange': 'Échange linguistique',
    'Meet other learners and local Bolivians in a relaxed setting': "Rencontrez d'autres apprenants et des Boliviens locaux dans un cadre détendu",
    'what people say': 'ce que les gens disent',
    'Guests love the <em>café</em>': 'Les visiteurs adorent le <em>café</em>',
    "A beautiful building with a lovely courtyard. The coffee is genuinely excellent — they clearly care about where it comes from. We sat in the patio for hours and nobody rushed us. Sucre's best kept secret.": "Un beau bâtiment avec une charmante cour. Le café est vraiment excellent. Nous sommes restés des heures dans le patio sans être pressés. Le secret le mieux gardé de Sucre.",
    'February 2026 · Tourist from the UK': 'Février 2026 · Touriste du Royaume-Uni',
    'Friendly café, great food. The Red Velvet cake was incredible. Came here every morning during my Spanish course and it became the highlight of my day. The WiFi is fast too — perfect for working remotely.': "Café accueillant, excellente nourriture. Le Red Velvet était incroyable. J'y venais chaque matin pendant mon cours d'espagnol et c'est devenu le point fort de ma journée.",
    'October 2025 · Me Gusta Spanish student': 'Octobre 2025 · Étudiant de Me Gusta Spanish',
    "I wasn't expecting much from a café attached to a language school, but this place completely surprised me. The Bolivian cold brew is extraordinary, and the carrot cake is one of the best I've ever had.": "Je n'attendais pas grand-chose d'un café attaché à une école de langues, mais cet endroit m'a complètement surpris. Le cold brew bolivien est extraordinaire.",
    'January 2026 · Digital nomad, Germany': 'Janvier 2026 · Nomade numérique, Allemagne',
    'come and find us': 'venez nous trouver',
    "We're in the <em>heart</em> of Sucre": 'Nous sommes au <em>cœur</em> de Sucre',
    "Me Gusta Café sits on Bolivar Street, just a short walk from Sucre's central plaza. Whether you're a student, visitor, or local — the door is always open.": "Le café Me Gusta se trouve sur la rue Bolivar, à quelques pas de la place centrale de Sucre. Que vous soyez étudiant, visiteur ou local — la porte est toujours ouverte.",
    'Opening Hours': "Heures d'ouverture",
    'Monday – Saturday': 'Lundi – Samedi',
    'Sunday': 'Dimanche',
    'Closed': 'Fermé',
    'WiFi': 'WiFi',
    'Free for all students &amp; guests': 'Gratuit pour tous les étudiants &amp; visiteurs',
    'Enrol at the school →': "S'inscrire à l'école →",
    'The Café': 'Le café',
    'School: Calle Dalence 146, Sucre': 'École : Calle Dalence 146, Sucre',
    'Café: Bolivar #603, Sucre': 'Café : Bolivar #603, Sucre',

    # ── ABOUT ──
    'our story ✨': 'notre histoire ✨',
    'Elizabeth &amp; Fernando, Sucre 2011 ✨': 'Elizabeth &amp; Fernando, Sucre 2011 ✨',
    'If you talk to a man in a language he understands, that goes to his head. If you talk to him in his <em>language</em>, that goes to his heart.': "Si vous parlez à un homme dans une langue qu'il comprend, cela va à sa tête. Si vous lui parlez dans <em>sa langue</em>, cela va à son cœur.",
    '— Nelson Mandela': '— Nelson Mandela',
    'Elizabeth, Co-founder ✨': 'Elizabeth, co-fondatrice ✨',
    'Fernando, Co-founder ✨': 'Fernando, co-fondateur ✨',
    'Demand from former students abroad pushes the school online. Me Gusta becomes one of the first Bolivian Spanish schools to offer live one-to-one online tuition at scale.': "La demande d'anciens étudiants à l'étranger pousse l'école en ligne. Me Gusta devient l'une des premières écoles d'espagnol boliviennes à offrir des cours en ligne en direct à grande échelle.",
    'Me Gusta Spanish has welcomed students from over 50 countries in person and online. The school, the methodology, and the warmth are exactly the same as they were in 2011 — just bigger.': "Me Gusta Spanish a accueilli des étudiants de plus de 50 pays en présentiel et en ligne. L'école, la méthodologie et la chaleur sont exactement les mêmes qu'en 2011 — juste en plus grand.",
    'from us, to you ✨': 'de nous, à vous ✨',

    # ── ACCOMMODATION ──
    'feel at home in Sucre': 'sentez-vous chez vous à Sucre',
    "Where you'll": 'Où vous',
    'stay': 'séjournerez',
    'Your accommodation is part of the learning experience. We offer two options — a warm host family placement or a comfortable student apartment — both steps from our school in the heart of Sucre.': "Votre hébergement fait partie de l'expérience d'apprentissage. Nous offrons deux options — un placement en famille d'accueil ou un appartement étudiant confortable — tous deux à quelques pas de notre école.",
    'Student Apartment': 'Appartement étudiant',
    'your home away from home ✨': 'votre chez-vous loin de chez vous ✨',
    'Option 1 — most popular': 'Option 1 — la plus populaire',
    'Live with a <em>Bolivian family</em>': 'Vivez avec une <em>famille bolivienne</em>',
    'Living with a Bolivian family is highly recommended. Not only do you practise more Spanish — you also learn about Bolivian culture, customs, and get to experience delicious Bolivian cuisine every single day.': "Vivre avec une famille bolivienne est fortement recommandé. Non seulement vous pratiquez plus d'espagnol — mais vous découvrez aussi la culture, les coutumes et la cuisine bolivienne chaque jour.",
    "All our host families are carefully selected and we maintain ongoing communication with them throughout your stay. Every family is located within a 10-minute walk of the school — so you're never far from class.": "Toutes nos familles d'accueil sont soigneusement sélectionnées. Chaque famille se trouve à 10 minutes à pied de l'école.",
    "what's included ✨": 'ce qui est inclus ✨',
    'Private room': 'Chambre privée',
    'Breakfast each morning': 'Petit-déjeuner chaque matin',
    'Lunch — the main meal of the day': 'Déjeuner — le repas principal de la journée',
    'Afternoon tea': 'Thé de l\'après-midi',
    "Within 10 minutes' walk of the school": "À 10 minutes à pied de l'école",
    'Total cultural immersion — 24/7 Spanish practice': "Immersion culturelle totale — pratique de l'espagnol 24h/24",
    'warm Bolivian hospitality 🏠': 'hospitalité bolivienne chaleureuse 🏠',
    'delicious Bolivian food 🍽️': 'délicieuse cuisine bolivienne 🍽️',
    'Option 2 — your own space': 'Option 2 — votre propre espace',
    'Student <em>Apartment</em>': '<em>Appartement</em> étudiant',
    "Prefer your own space? Our student apartment is a comfortable, social base right in the heart of Sucre. You'll be surrounded by other international students — great for practising Spanish and making friends from around the world.": "Vous préférez votre propre espace ? Notre appartement étudiant est une base confortable et sociale au cœur de Sucre. Vous serez entouré d'autres étudiants internationaux.",
    'Breakfast is included in both options. Choose between a shared or private room depending on your preference and budget.': "Le petit-déjeuner est inclus dans les deux options. Choisissez entre une chambre partagée ou privée selon vos préférences et votre budget.",
    'comfortable &amp; social ✨': 'confortable &amp; convivial ✨',
    'Shared Room': 'Chambre partagée',
    'Bunk beds': 'Lits superposés',
    'Shared bathroom': 'Salle de bain partagée',
    'Breakfast included': 'Petit-déjeuner inclus',
    'Maximum 4 persons': 'Maximum 4 personnes',
    'Private Room': 'Chambre privée',
    'Double bed': 'Lit double',
    'Private bathroom': 'Salle de bain privée',
    'Couple rate: US$29/night': 'Tarif couple : 29 US$/nuit',
    'travelling as a couple? great value at US$29 together 💕': 'en couple ? excellent tarif à 29 US$ ensemble 💕',
    'Also available on': 'Aussi disponible sur',
    'Book the student apartment through your favourite platform': 'Réservez l\'appartement étudiant via votre plateforme préférée',
    'why where you sleep matters...': 'pourquoi le lieu de votre séjour compte...',
    'Your accommodation is part of your <em>Spanish journey</em>': "Votre hébergement fait partie de votre <em>parcours en espagnol</em>",
    'More Speaking Time': 'Plus de temps de parole',
    'Every conversation at the dinner table, at the market, at home — is Spanish practice. Students who live locally progress significantly faster.': "Chaque conversation à table, au marché, à la maison — est de la pratique d'espagnol. Les étudiants qui vivent localement progressent nettement plus vite.",
    'Real Cultural Immersion': 'Véritable immersion culturelle',
    'Bolivian culture, food and traditions become part of your daily life — not just something you read about in a classroom.': "La culture, la cuisine et les traditions boliviennes deviennent partie de votre quotidien — pas juste quelque chose lu en classe.",
    'Lasting Friendships': 'Amitiés durables',
    "Students who stay with families often leave with friendships that last a lifetime. It's one of the most-mentioned highlights in our student reviews.": "Les étudiants qui séjournent en famille repartent souvent avec des amitiés pour la vie. C'est l'un des points forts les plus mentionnés dans nos avis.",
    'Ask Us About Accommodation →': "Nous contacter pour l'hébergement →",
    'Ready to <em>book</em> your stay?': 'Prêt à <em>réserver</em> votre séjour ?',
    "Get in touch and we'll help you find the best accommodation option for your budget, timeline and learning goals. We're friendly — just say hola.": "Contactez-nous et nous vous aiderons à trouver la meilleure option d'hébergement selon votre budget et vos objectifs. Nous sommes accueillants — dites juste hola.",
    "we'll get back to you same day ✨": 'nous vous répondrons le jour même ✨',
    'Shared Room — US$12': 'Chambre partagée — 12 US$',
    'Private Room — US$25': 'Chambre privée — 25 US$',

    # ── FAQS ──
    "we've got answers ✨": 'nous avons les réponses ✨',
    'Frequently <em>asked</em> questions': 'Questions <em>fréquemment</em> posées',
    'Everything you need to know before you arrive — from how to get to Sucre to what happens if you want to change your teacher.': "Tout ce que vous devez savoir avant votre arrivée — de comment arriver à Sucre à ce qui se passe si vous voulez changer de professeur.",
    'When can I start classes?': 'Quand puis-je commencer les cours ?',
    "You can start on any Monday of the year — we don't have fixed enrolment dates. If you're arriving mid-week, just let us know and we'll arrange for you to start on your first full day. We're flexible and we'll work around you.": "Vous pouvez commencer n'importe quel lundi de l'année — nous n'avons pas de dates d'inscription fixes. Si vous arrivez en milieu de semaine, dites-le nous et nous organiserons votre début.",
    'Do you offer discounts for longer stays?': 'Offrez-vous des réductions pour les séjours plus longs ?',
    'Yes — students who enrol for 3 weeks or more receive a discount on their course fees. The longer you stay, the better the value. Contact us for a personalised quote based on your study plan and number of hours per week.': "Oui — les étudiants qui s'inscrivent pour 3 semaines ou plus bénéficient d'une réduction. Plus vous restez, meilleur est le tarif. Contactez-nous pour un devis personnalisé.",
    'How do you match me with a class level?': 'Comment déterminez-vous mon niveau ?',
    "Before you start, we'll have a short conversation with you — either in person or via email — to assess your level. We consider your speaking ability, listening comprehension, and grammar instincts. You'll never be placed in a class that's too easy or too difficult. If you're part of a couple or group travelling together and have different levels, we'll place you in separate classes to ensure each of you makes the best possible progress.": "Avant de commencer, nous aurons une courte conversation avec vous pour évaluer votre niveau. Nous considérons votre capacité à parler, votre compréhension orale et vos instincts grammaticaux. Vous ne serez jamais placé dans un cours trop facile ou trop difficile.",
    'Can couples or friends study together even if their levels are different?': 'Les couples ou amis peuvent-ils étudier ensemble même si leurs niveaux sont différents ?',
    "We always recommend placing students at their correct level — even if that means separating friends or partners during class time. Learning at the wrong level slows everyone down. Outside of class, you'll still be experiencing Sucre together. If both students are at a genuinely similar level, we can of course put them together.": "Nous recommandons toujours de placer les étudiants à leur bon niveau — même si cela signifie séparer les amis pendant les cours. Apprendre au mauvais niveau ralentit tout le monde. En dehors des cours, vous profiterez de Sucre ensemble.",
    'How are group classes formed?': 'Comment les cours de groupe sont-ils formés ?',
    'Group classes are formed organically based on who is at the school at the same time and at the same level. Class sizes are small — a maximum of 4-5 students — so the atmosphere remains personal and interactive. Groups are never mixed across significantly different levels.': "Les cours de groupe se forment naturellement selon les étudiants présents au même moment et au même niveau. Les groupes sont petits — maximum 4-5 étudiants — pour une atmosphère personnelle et interactive.",
    "Can I change my teacher if I don't feel we're a good match?": 'Puis-je changer de professeur si je sens que ça ne colle pas ?',
    "Absolutely — and please do tell us if something isn't working. We'd much rather know early and make a change than have you spend a week with a teacher who isn't right for you. Just speak to Fernando or Elizabeth and we'll sort it out quietly and without any awkwardness.": "Absolument — et n'hésitez pas à nous le dire si quelque chose ne fonctionne pas. Nous préférons le savoir tôt et faire un changement. Parlez à Fernando ou Elizabeth et nous réglerons cela discrètement.",
    '\u200d\u200d Families &amp; Children': '\u200d\u200d Familles &amp; Enfants',
    'Can children study at Me Gusta? From what age?': 'Les enfants peuvent-ils étudier à Me Gusta ? À partir de quel âge ?',
    "Yes! We welcome children from age 6 onwards. Our children's classes are adapted to shorter attention spans, with more games, visual materials, and interactive activities. Families with children of different ages are welcome — we'll create a schedule that works for everyone.": "Oui ! Nous accueillons les enfants à partir de 6 ans. Nos cours pour enfants sont adaptés avec plus de jeux, de matériel visuel et d'activités interactives. Les familles avec des enfants d'âges différents sont les bienvenues.",
    'How do I get to Sucre?': 'Comment arriver à Sucre ?',
    "The easiest way to reach Sucre is by flying. Domestic flights from La Paz, Santa Cruz, and Cochabamba are operated by BOA (Boliviana de Aviación), Amaszonas, and Ecojet — journey times are around 45 minutes to 1 hour. Buses are also available from most major Bolivian cities; the overnight bus from La Paz takes around 14–16 hours and is a budget-friendly option. Sucre's airport (Juana Azurduy de Padilla) is about 5 km from the city centre.": "Le plus simple pour arriver à Sucre est l'avion. Des vols intérieurs depuis La Paz, Santa Cruz et Cochabamba sont opérés par BOA, Amaszonas et Ecojet — environ 45 min à 1 heure. Des bus sont aussi disponibles ; le bus de nuit depuis La Paz prend environ 14-16 heures.",
    'Do you accept credit card payments?': 'Acceptez-vous les paiements par carte de crédit ?',
    'Yes, we accept Visa and Mastercard. Please note that a 2.5% surcharge applies to all card transactions to cover processing fees. We also accept cash in Bolivianos or US Dollars, and bank transfer. Most students find it easiest to pay in cash on arrival.': "Oui, nous acceptons Visa et Mastercard. Veuillez noter qu'un supplément de 2,5 % s'applique. Nous acceptons aussi les espèces en Bolivianos ou en dollars US, et les virements bancaires.",
    'Do I need to pay in advance to secure my place?': 'Dois-je payer à l\'avance pour réserver ma place ?',
    "We ask for a small deposit to secure your booking, especially during busy seasons (June–August and December–January). The balance can be paid on arrival. If you're booking more than 4 weeks in advance, we'll be in touch to confirm the deposit amount — it's typically the equivalent of one week's tuition.": "Nous demandons un petit acompte pour sécuriser votre réservation, surtout pendant les saisons chargées (juin-août et décembre-janvier). Le solde peut être payé à l'arrivée.",
    ' Accommodation': ' Hébergement',
    'Do you recommend host family accommodation?': "Recommandez-vous l'hébergement en famille d'accueil ?",
    "Wholeheartedly — yes. Students who stay with a host family make dramatically faster progress because they're speaking Spanish outside of class every single day. Mealtimes, small talk in the kitchen, watching TV together — it all adds up. We personally vet all of our host families and stay in close contact with them. It's not just accommodation; it's part of the immersion.": "Absolument — oui. Les étudiants en famille d'accueil progressent beaucoup plus vite car ils parlent espagnol en dehors des cours chaque jour. Les repas, les discussions dans la cuisine — tout compte. Nous sélectionnons personnellement toutes nos familles d'accueil.",
    'Do you organise activities outside of class?': 'Organisez-vous des activités en dehors des cours ?',
    'Yes — we organise a regular programme of optional activities to help you practise your Spanish in real contexts and explore Sucre and the surrounding area. Past activities have included cooking classes, market visits, day trips to Tarabuco and Potosí, salsa lessons, and guided city walks. These are all run in Spanish as much as possible.': "Oui — nous organisons un programme régulier d'activités optionnelles pour pratiquer votre espagnol en contexte réel et explorer Sucre. Les activités passées incluent cours de cuisine, visites de marché, excursions à Tarabuco et Potosí, cours de salsa et visites guidées.",
    'How much do activities cost?': 'Combien coûtent les activités ?',
    'Most activities are priced at around US$15 per person, which covers any entrance fees, materials, or transport. Some shorter activities (like a city walk) are completely free. We keep prices as low as possible — we want everyone to be able to join in, regardless of budget.': "La plupart des activités coûtent environ 15 US$ par personne, ce qui couvre les frais d'entrée, le matériel ou le transport. Certaines activités plus courtes sont gratuites. Nous gardons les prix aussi bas que possible.",
    "didn't find your answer? ✨": "vous n'avez pas trouvé votre réponse ? ✨",
    'Just ask us directly': 'Demandez-nous directement',
    "We're always happy to answer questions — no question is too small or too specific. Drop us a message and we'll get back to you within 24 hours.": "Nous sommes toujours heureux de répondre à vos questions — aucune question n'est trop petite. Envoyez-nous un message et nous vous répondrons sous 24 heures.",
    'Send us a message →': 'Envoyez-nous un message →',

    # ── BLOG ──
    'stories, tips &amp; Bolivia ✨': 'histoires, conseils &amp; Bolivie ✨',
    'The Me Gusta <em>Blog</em>': 'Le <em>blog</em> Me Gusta',
    'Tips for learning Spanish, stories from our students, life in Sucre, and everything you need to know about Bolivia before you arrive.': "Conseils pour apprendre l'espagnol, histoires de nos étudiants, vie à Sucre, et tout ce que vous devez savoir sur la Bolivie avant d'arriver.",
    'Learning tips': "Conseils d'apprentissage",
    'Why Bolivian Spanish is the <em>best</em> in Latin America to learn': "Pourquoi l'espagnol bolivien est le <em>meilleur</em> d'Amérique latine à apprendre",
    "You've probably heard that Spanish is spoken differently across Latin America. What you might not know is that Bolivia — and Sucre in particular — has a quiet reputation among language teachers and linguists as the clearest, most 'neutral' Spanish on the continent. Here's why.": "Vous avez probablement entendu que l'espagnol se parle différemment en Amérique latine. Ce que vous ne savez peut-être pas, c'est que la Bolivie — et Sucre en particulier — a la réputation d'avoir l'espagnol le plus clair et le plus \"neutre\" du continent.",
    'Elizabeth': 'Elizabeth',
    'March 2025': 'Mars 2025',
    'Bolivia &amp; Sucre': 'Bolivie &amp; Sucre',
    'Your first week in Sucre: a practical guide': 'Votre première semaine à Sucre : guide pratique',
    'Everything you need to know before you arrive — from the altitude (3,000m above sea level, take it slow!) to where to eat, how to get around, and the five things we wish someone had told us.': "Tout ce que vous devez savoir avant d'arriver — de l'altitude (3 000 m, allez-y doucement !) aux endroits où manger et comment se déplacer.",
    'Fernando': 'Fernando',
    'Feb 2025': 'Fév 2025',
    'The 5 habits of students who learn Spanish fastest': "Les 5 habitudes des étudiants qui apprennent l'espagnol le plus vite",
    "After 14 years of teaching, Elizabeth has noticed clear patterns in the students who make rapid progress. It's not about intelligence — it's about what you do outside the classroom.": "Après 14 ans d'enseignement, Elizabeth a remarqué des tendances claires chez les étudiants qui progressent rapidement. Ce n'est pas une question d'intelligence — c'est ce que vous faites en dehors de la salle de classe.",
    'Jan 2025': 'Jan 2025',
    "10 Spanish phrases you'll use every day in Bolivia": "10 phrases en espagnol que vous utiliserez chaque jour en Bolivie",
    "Bolivian Spanish has its own lovely quirks — words and expressions that textbooks never teach you. Learn these ten before you arrive and you'll be ordering soup at the market like a local within days.": "L'espagnol bolivien a ses propres expressions charmantes — des mots que les manuels ne vous enseignent jamais. Apprenez ces dix-là avant d'arriver et vous commanderez de la soupe au marché comme un local.",
    'Andrea': 'Andrea',
    'Dec 2024': 'Déc 2024',
    'Student stories': "Histoires d'étudiants",
    "From zero to conversational in four weeks: Tom's story": "De zéro à conversationnel en quatre semaines : l'histoire de Tom",
    "Tom arrived in Sucre in October with no Spanish at all. Six weeks later, he was chatting with his host family over dinner and negotiating with market vendors. Here's how he did it.": "Tom est arrivé à Sucre en octobre sans aucun espagnol. Six semaines plus tard, il discutait avec sa famille d'accueil et négociait avec les vendeurs du marché.",
    'Tom (student)': 'Tom (étudiant)',
    'Nov 2024': 'Nov 2024',
    'Online learning': 'Apprentissage en ligne',
    'How to get the most out of online Spanish classes': "Comment tirer le meilleur parti des cours d'espagnol en ligne",
    'Online classes can be just as effective as in-person — if you approach them the right way. Yhamyle shares her top tips for students who want to make real progress from home.': "Les cours en ligne peuvent être aussi efficaces qu'en présentiel — si vous les abordez de la bonne façon. Yhamyle partage ses meilleurs conseils pour progresser depuis chez soi.",
    'Yhamyle': 'Yhamyle',
    'Oct 2024': 'Oct 2024',
    "Why Sucre is South America's best-kept secret": "Pourquoi Sucre est le secret le mieux gardé d'Amérique du Sud",
    "Every traveller who comes to Sucre says the same thing: why didn't anyone tell me about this place? We've been saying it for years. Here's our love letter to the White City.": "Chaque voyageur qui vient à Sucre dit la même chose : pourquoi personne ne m'a parlé de cet endroit ? Nous le disons depuis des années. Voici notre lettre d'amour à la Ville Blanche.",
    'Sep 2024': 'Sep 2024',
    'more coming soon ✨': "d'autres articles bientôt ✨",
    'New posts every month — from Elizabeth, Fernando, and the whole team': "Nouveaux articles chaque mois — d'Elizabeth, Fernando et toute l'équipe",
    'Tips on learning Spanish, life in Bolivia, student stories, teacher perspectives, and everything in between.': "Conseils pour apprendre l'espagnol, la vie en Bolivie, histoires d'étudiants, perspectives des professeurs, et tout le reste.",

    # ── CONTACT ──
    'Online classes': 'Cours en ligne',
}

def add_data_fr(html):
    def replacer(m):
        en_val = m.group(1)
        after_pos = m.end()
        after = html[after_pos:after_pos+50]
        tag_rest = after.split('>')[0] if '>' in after else after
        if 'data-fr=' in tag_rest:
            return m.group(0)
        fr_val = FR.get(en_val)
        if fr_val is None:
            return m.group(0)
        return f'{m.group(0)} data-fr="{fr_val}"'
    result = re.sub(r'data-en="([^"]+)" data-es="[^"]*"', replacer, html)
    def replacer2(m):
        en_val = m.group(1)
        after_pos = m.end()
        after = result[after_pos:after_pos+50]
        tag_rest = after.split('>')[0] if '>' in after else after
        if 'data-es=' in tag_rest or 'data-fr=' in tag_rest:
            return m.group(0)
        fr_val = FR.get(en_val)
        if fr_val is None:
            return m.group(0)
        return f'{m.group(0)} data-fr="{fr_val}"'
    result = re.sub(r'data-en="([^"]+)"', replacer2, result)
    return result

total = 0
for page in PAGES:
    path = os.path.join(BASE, page)
    with open(path) as f:
        old = f.read()
    new = add_data_fr(old)
    added = new.count('data-fr=') - old.count('data-fr=')
    total += added
    with open(path, 'w') as f:
        f.write(new)
    print(f'✓ {page} (+{added})')

print(f'\nTotal: +{total} data-fr added')

# Count remaining
missing = 0
for page in PAGES:
    with open(os.path.join(BASE, page)) as f:
        content = f.read()
    for m in re.finditer(r'data-en="([^"]+)"', content):
        after = content[m.end():m.end()+200]
        tag_rest = after.split('>')[0] if '>' in after else after
        if 'data-fr=' not in tag_rest:
            missing += 1
print(f'Remaining without data-fr: {missing}')
